#!/bin/bash
FILE=bin/CPU.out
make clean all
make
if test -f "./$FILE"; then

    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=yes --show-reachable=yes --num-callers=20 --track-origins=yes ./$FILE ./cfg/CPU.config
fi